<?php
require_once __DIR__ . '/../includes/helpers.php';
require_once __DIR__ . '/../config/database.php';
requireAdminLogin();

$db = getDB();
$status = $_GET['status'] ?? '';

$where = [];
$params = [];
if ($status) { $where[] = "ed.employment_status = ?"; $params[] = $status; }
$whereSQL = $where ? 'WHERE ' . implode(' AND ', $where) : '';

$stmt = $db->prepare("
    SELECT g.reg_number, g.full_name, g.email, g.phone, g.course, g.graduation_year, ed.*
    FROM employment_details ed
    JOIN graduates g ON ed.graduate_id = g.id
    {$whereSQL}
    ORDER BY g.full_name ASC
");
$stmt->execute($params);
$employment_data = $stmt->fetchAll();

$status_label = match($status) {
    'employed' => 'Employed',
    'self_employed' => 'Self Employed',
    'unemployed' => 'Unemployed',
    'further_studies' => 'Further Studies',
    'seeking' => 'Seeking',
    default => 'All Graduates'
};

$generated_date = date('F d, Y \a\t H:i');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employment Report - <?= htmlspecialchars($status_label) ?></title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size: 11px; color: #333; padding: 20px; }
        
        .report-header { text-align: center; margin-bottom: 25px; padding-bottom: 15px; border-bottom: 3px solid #1a5276; }
        .report-header h1 { font-size: 20px; color: #1a5276; margin-bottom: 5px; }
        .report-header h2 { font-size: 14px; color: #555; font-weight: normal; margin-bottom: 5px; }
        .report-header .subtitle { font-size: 12px; color: #777; }
        .report-meta { display: flex; justify-content: space-between; margin-bottom: 20px; font-size: 11px; color: #555; }
        
        .stats-summary { display: flex; gap: 15px; margin-bottom: 20px; }
        .stat-box { flex: 1; background: #f4f6f9; border: 1px solid #ddd; padding: 10px; text-align: center; border-radius: 4px; }
        .stat-box .number { font-size: 22px; font-weight: bold; color: #1a5276; }
        .stat-box .label { font-size: 10px; color: #666; text-transform: uppercase; }
        
        table { width: 100%; border-collapse: collapse; margin-top: 15px; page-break-inside: auto; }
        thead { display: table-header-group; }
        tr { page-break-inside: avoid; }
        th { background: #1a5276; color: white; padding: 8px 6px; text-align: left; font-size: 10px; text-transform: uppercase; border-right: 1px solid rgba(255,255,255,0.2); }
        th:last-child { border-right: none; }
        td { padding: 7px 6px; border-bottom: 1px solid #e0e0e0; font-size: 10px; }
        tr:nth-child(even) { background: #f9f9f9; }
        
        .status-badge { display: inline-block; padding: 2px 8px; border-radius: 3px; font-size: 9px; font-weight: bold; text-transform: uppercase; }
        .status-employed { background: #d4edda; color: #155724; }
        .status-self_employed { background: #d1ecf1; color: #0c5460; }
        .status-unemployed { background: #f8d7da; color: #721c24; }
        .status-further_studies { background: #cce5ff; color: #004085; }
        .status-seeking { background: #fff3cd; color: #856404; }
        
        .footer { margin-top: 30px; padding-top: 15px; border-top: 2px solid #1a5276; text-align: center; font-size: 9px; color: #999; }
        
        @media print {
            body { padding: 0; font-size: 10px; }
            @page { margin: 15mm; size: landscape; }
            .report-header { border-bottom-width: 2px; }
        }
    </style>
</head>
<body onload="window.print()">
    <div class="report-header">
        <h1><i class="bi bi-mortarboard-fill"></i> RUCU Graduate Employment Tracking System</h1>
        <h2>Employment Report - <?= htmlspecialchars($status_label) ?> Graduates</h2>
        <div class="subtitle">Ruaha Catholic University (RUCU) - Admin Panel</div>
    </div>
    
    <div class="report-meta">
        <span><strong>Generated:</strong> <?= $generated_date ?></span>
        <span><strong>Generated by:</strong> <?= htmlspecialchars($_SESSION['admin_name'] ?? 'Admin') ?></span>
        <span><strong>Total Records:</strong> <?= count($employment_data) ?></span>
    </div>
    
    <div class="stats-summary">
        <div class="stat-box">
            <div class="number"><?= count($employment_data) ?></div>
            <div class="label"><?= htmlspecialchars($status_label) ?></div>
        </div>
        <div class="stat-box">
            <div class="number"><?= $db->query("SELECT COUNT(*) FROM graduates")->fetchColumn() ?></div>
            <div class="label">Total Graduates</div>
        </div>
        <div class="stat-box">
            <div class="number"><?= $db->query("SELECT COUNT(DISTINCT company_name) FROM employment_details WHERE company_name IS NOT NULL")->fetchColumn() ?></div>
            <div class="label">Organizations</div>
        </div>
        <div class="stat-box">
            <div class="number"><?= $db->query("SELECT COUNT(DISTINCT location) FROM employment_details WHERE location IS NOT NULL")->fetchColumn() ?></div>
            <div class="label">Locations</div>
        </div>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Reg No.</th>
                <th>Name</th>
                <th>Course</th>
                <th>Year</th>
                <th>Status</th>
                <th>Company</th>
                <th>Job Title</th>
                <th>Type</th>
                <th>Salary Range</th>
                <th>Location</th>
                <th>Start Date</th>
                <th>Phone</th>
            </tr>
        </thead>
        <tbody>
            <?php $i = 1; foreach ($employment_data as $e): ?>
            <tr>
                <td><?= $i++ ?></td>
                <td><?= htmlspecialchars($e['reg_number']) ?></td>
                <td><?= htmlspecialchars($e['full_name']) ?></td>
                <td><?= htmlspecialchars($e['course']) ?></td>
                <td><?= $e['graduation_year'] ?></td>
                <td><span class="status-badge status-<?= $e['employment_status'] ?>"><?= str_replace('_', ' ', ucfirst($e['employment_status'])) ?></span></td>
                <td><?= htmlspecialchars($e['company_name'] ?? '-') ?></td>
                <td><?= htmlspecialchars($e['job_title'] ?? '-') ?></td>
                <td><?= $e['organization_type'] ? ucfirst(str_replace('_', ' ', $e['organization_type'])) : '-' ?></td>
                <td><?= htmlspecialchars($e['salary_range'] ?? '-') ?></td>
                <td><?= htmlspecialchars($e['location'] ?? '-') ?></td>
                <td><?= $e['start_date'] ? date('M d, Y', strtotime($e['start_date'])) : '-' ?></td>
                <td><?= htmlspecialchars($e['phone'] ?? '-') ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    
    <div class="footer">
        <p>&copy; <?= date('Y') ?> Ruaha Catholic University (RUCU) - Graduate Employment Tracking & Verification System</p>
        <p>This report is confidential and intended for internal use only.</p>
    </div>
</body>
</html>
